#' Adding Columns to the DHS Catalog
#'
#' \code{expand_catalogue} adds file type, version number and file format
#' information to the the catalog as generated by the
#' \link[lodown]{\code{get_catalog}} function.
#'
#' @param x a data frame catalog has outputed by \link[lodown]{\code{get_catalog}}.
#'
#' @return a data frame catalog has outputed by \link[lodown]{\code{get_catalog}},
#' with three additional columns: \code{file_type}, \code{version_number} and
#' \code{file_format}. See example in the documentation of
#' \link[lodown]{\code{with_profile}}.
#'
#' @export
#'
expand_catalogue <- function(x) {
  bind_cols(x, split_code(get_code(x$full_url)))
}
