#' Adding Columns to the DHS Catalog
#'
#' \code{expand_catalogue} adds file type, version number and file format
#' information to the the catalog as generated by the
#' \code{\link[lodown]{get_catalog}} function.
#'
#' @param x a data frame catalog has outputed by \code{\link[lodown]{get_catalog}}.
#'
#' @return a data frame catalog has outputed by \code{\link[lodown]{get_catalog}},
#' with three additional columns: \code{file_type}, \code{version_number} and
#' \code{file_format}. See example in the documentation of
#' \code{\link[lodown]{with_profile}}.
#'
#' @export
#'
expand_catalogue <- function(x) {
  bind_cols(x, split_code(get_code(x$full_url)))
}
