get_code <- function(x) {
  x %>%
    sub("^.*Filename=", "", .) %>%
    sub("\\.ZIP.*$"   , "", .)
}


split_code <- function(x) {
  require(magrittr) # %>%
  x %<>% sub("^..", "", .) # the first 2 characters are the country code.
  sapply(seq(1, max(nchar(x)), 2), function(i) substr(x, i, i + 1)) %>%
    as.data.frame() %>%
    setNames(c("file_type", "version_number", "file_format"))
}


#' Adding Columns to the DHS Catalog
#'
#' \code{expand_catalogue} adds file type, version number and file format
#' information to the the catalog as generated by the
#' \code{\link[lodown]{get_catalog}} function.
#'
#' @param x a data frame catalog has outputed by \code{\link[lodown]{get_catalog}}.
#'
#' @return a data frame catalog has outputed by \code{\link[lodown]{get_catalog}},
#' with three additional columns: \code{file_type}, \code{version_number} and
#' \code{file_format}. See example in the documentation of
#' \code{\link{with_profile}}.
#'
#' @importFrom dplyr bind_cols
#' @importFrom lodown get_catalog
#'
#' @noRd
#'
expand_catalogue <- function(x) {
  file_name <- get_code(x$full_url)
  bind_cols(x, file_name = file_name, split_code(file_name))
}
